services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: financial-tracker-app
    container_name: financial-tracker-web
    restart: unless-stopped
    ports:
      - "8082:80"
    env_file:
      - .env
    # Pintu akses ke VPS host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./storage:/var/www/storage
